source 'git@github.com:Vonage/PrivateCocoapodsSpecs.git'
# source 'git@github.com:CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'GetStartedInAppVoice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for GetStartedInAppVoice
  pod 'NexmoClient'

end
